### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by DenisSch** [DenisSch/Quantification#23]
```
(base) [as773@compute-e-16-229 e3bab0f316d22adf95d950b86ebb60]$ cat .command.log
{'masks': ['cellMask.tif'], 'image': 'unmicst-31.tif', 'channel_names': 'markers.csv', 'output': '.'}
Extracting single-cell data for unmicst-31.tif...
Finished 0
Finished 1
Finished 2
Finished 3
Finished 4
Finished 5
Finished 6
Finished 7
Finished 8
Finished 9
Finished 10
Finished 11
Finished 12
Finished 13
Finished 14
Finished 15
Finished 16
Finished 17
Finished 18
Finished 19
Finished 20
Finished 21
Finished 22
Finished 23
Finished 24
Finished 25
Finished 26
Finished 27
Finished 28
Finished 29
Finished 30
Finished 31
Traceback (most recent call last):
  File "/n/groups/lsp/mcmicro/2020-07-27/quantification/CommandSingleCellExtraction.py", line 11, in <module>
    SingleCellDataExtraction.MultiExtractSingleCells(**args)
  File "/n/groups/lsp/mcmicro/2020-07-27/quantification/SingleCellDataExtraction.py", line 260, in MultiExtractSingleCells
    ExtractSingleCells(masks,image,channel_names,output)
  File "/n/groups/lsp/mcmicro/2020-07-27/quantification/SingleCellDataExtraction.py", line 245, in ExtractSingleCells
    scdata_z = MaskZstack(masks_loaded,image,channel_names_loaded_checked)
  File "/n/groups/lsp/mcmicro/2020-07-27/quantification/SingleCellDataExtraction.py", line 154, in MaskZstack
    new_names = [channel_names_loaded[i]+"_"+str(nm) for i in range(len(channel_names_loaded))]
  File "/n/groups/lsp/mcmicro/2020-07-27/quantification/SingleCellDataExtraction.py", line 154, in <listcomp>
    new_names = [channel_names_loaded[i]+"_"+str(nm) for i in range(len(channel_names_loaded))]
TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Comment by DenisSch** [comment]
There seems to be a "space" in the marker.csv that causes this issue!

**Comment by DenisSch** [comment]
It seems to also convert `NA` to `nan`

```
>>> channel_names_loaded
       DNA0
0    Rabbit
1       Rat
2       NaN
3      DNA1
...
