### ISSUE TITLE
Exemplar-001 fails on 02

### ISSUE THREAD

**Issue by DenisSch** [DenisSch/Quantification#6]
```
(base) [as773@compute-e-16-237 ~]$ nextflow run labsyspharm/mcmicro-nf --in ~/test/exemplar-001 --skip_ashlar -profile O2
N E X T F L O W  ~  version 20.01.0
Launching `labsyspharm/mcmicro-nf` [mighty_elion] - revision: 18725b5a57 [master]
executor >  slurm (1)
[-        ] process > illumination   -
[-        ] process > ashlar         -
[-        ] process > dearray        -
[cf/807300] process > unmicst        [100%] 1 of 1, cached: 1 ✔
[3d/c138f8] process > s3seg          [100%] 1 of 1, cached: 1 ✔
[c3/c1e325] process > quantification [100%] 1 of 1, failed: 1 ✘
Error executing process > 'quantification (1)'
Caused by:
  Process `quantification (1)` terminated with an error exit status (1)
Command executed:
  python /n/groups/lsp/mcmicro/quantification/CommandSingleCellExtraction.py     --mask cellMask.tif --image exemplar-001.ome.tif     --output . --channel_names markers.csv
Command exit status:
  1
Command output:
  {'mask': 'cellMask.tif', 'image': 'exemplar-001.ome.tif', 'channel_names': 'markers.csv', 'output': '.'}
  Extracting sinle-cell data for exemplar-001.ome.tif...
Command error:
  Traceback (most recent call last):
    File "/n/groups/lsp/mcmicro/quantification/CommandSingleCellExtraction.py", line 11, in <module>
      SingleCellDataExtraction.MultiExtractSingleCells(**args)
    File "/n/groups/lsp/mcmicro/quantification/SingleCellDataExtraction.py", line 177, in MultiExtractSingleCells
      ExtractSingleCells(mask,image,channel_names,output)
    File "/n/groups/lsp/mcmicro/quantification/SingleCellDataExtraction.py", line 162, in ExtractSingleCells
      mask_loaded, image_loaded, channel_names_loaded = PrepareData(mask,image,channel_names)
    File "/n/groups/lsp/mcmicro/quantification/SingleCellDataExtraction.py", line 91, in PrepareData
      image_loaded = image_loaded.reshape((image_loaded.shape[0],image_loaded.shape[3],image_loaded.shape[4]))
  IndexError: tuple index out of range
```

**Comment by DenisSch** [comment]
Wrong CSV file used

**Comment by DenisSch** [comment]
Issue remains after marker.csv fix.
